"""initial schema

Revision ID: a4e9a32da2b8
Revises: 
Create Date: 2026-09-19 00:44:13.266897
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


revision = 'a4e9a32da2b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Spatial (GiST) indexes are created by GeoAlchemy2 itself on create_table;
    # declaring them here too fails with DuplicateTable.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('primary_sport', sa.String(length=20), nullable=False),
    sa.Column('pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('typical_distance_m', sa.Float(), nullable=True),
    sa.Column('persona_text', sa.Text(), nullable=True),
    sa.Column('self_declared_age', sa.Integer(), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_is_seeded'), 'athlete', ['is_seeded'], unique=False)
    op.create_index(op.f('ix_athlete_strava_id'), 'athlete', ['strava_id'], unique=True)
    op.create_table('kb_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('start_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('route', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('start_time_local', sa.DateTime(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('moving_time_s', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'strava_activity_id', name='uq_activity_strava')
    )
    op.create_index(op.f('ix_activity_athlete_id'), 'activity', ['athlete_id'], unique=False)
    op.create_table('athlete_embedding',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('card_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('home_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_base_athlete_id'), 'home_base', ['athlete_id'], unique=False)
    op.create_table('match_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=False),
    sa.Column('relaxations_json', sa.Text(), nullable=False),
    sa.Column('result_ids_json', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_recipient_id'), 'message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_table('strava_token',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strava_token')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_recipient_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('match_request')
    op.drop_index(op.f('ix_home_base_athlete_id'), table_name='home_base')
    op.drop_table('home_base')
    op.drop_table('athlete_embedding')
    op.drop_index(op.f('ix_activity_athlete_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_table('kb_chunk')
    op.drop_index(op.f('ix_athlete_strava_id'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_is_seeded'), table_name='athlete')
    op.drop_table('athlete')
    # ### end Alembic commands ###
